dist: trusty
language: php

php:
  - 7.1
  - 7.2
  - nightly

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{,.disabled} || echo "xdebug not available"
  - travis_retry composer self-update

install: composer install --dev --prefer-dist

script: bin/phpunit --group default,ReactPromise

jobs:
  allow_failures:
    - php: nightly

  include:
    - stage: Test
      env: DEPENDENCIES=low
      install:
        - travis_retry composer update --prefer-dist --prefer-lowest

    - stage: Test
      env: COVERAGE
      before_script:
        - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{.disabled,}
        - if [[ ! $(php -m | grep -si xdebug) ]]; then echo "xdebug required for coverage"; exit 1; fi
      script:
        - bin/phpunit --coverage-clover clover.xml
      after_script:
        - wget https://scrutinizer-ci.com/ocular.phar
        - php ocular.phar code-coverage:upload --format=php-clover clover.xml

    - stage: Code Quality
      php: 7.1
      install: travis_retry composer install --prefer-dist
      script:
        - ./vendor/bin/phpcs

    - stage: Code Quality
      php: 7.2
      env: STATIC_ANALYSIS
      install: travis_retry composer install --prefer-dist
      script: composer static-analysis
